### ISSUE TITLE
Caesar类：实现Encode函数

### ISSUE THREAD

**Issue by yah01** [yah01/CipherBreaker#3]
1. 若plain给定了值，则修改Plain字段
2. 若encodeKey给定了值，则修改EncodeKey属性
3. 使用EncodeKey作为密钥，加密Plain，结果存储在Cipher中

**Comment by sssssssssssssssssa** [comment]
龚如晗认领

**Comment by yah01** [comment]
@sssssssssssssssssa 注意一下在这里这个算法的密钥是一个0~25的整数，但是我们存储为字符串。比如EncodeKey=“1”，明文Plain=“ABC”，那么应该加密出来的密文Cipher就应该是"BCD"
